# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xhep7DTYuVlKdjbX0PWz252g_gpTjG7c
"""

import requests

# Make a request to the API endpoint
response = requests.get('https://randomuser.me/api/')
data = response.json()

# Extract relevant information from the JSON response
results = data['results']
for result in results:
    name = result['name']['first']
    last_name = result['name']['last']
    gender = result['gender']
    email = result['email']
    
    # Print the extracted information
    print(f"Name: {name} {last_name}")
    print(f"Gender: {gender}")
    print(f"Email: {email}")
    print("--------------------")

import requests 
response = requests.get('https://randomuser.me/api')
data  = response.json()
results = data['results']
for result in results:
  gender = result['gender']

import requests

# Make a request to the API endpoint
response = requests.get('https://randomuser.me/api/1.4/')
data = response.json()

# Extract relevant information from the JSON response
results = data['results']
for result in results:
    user_info = result['name']
    
    # Print the key-value pairs from the dictionary
    for key, value in user_info.items():
        print(f"{key}: {value}")

https://randomuser.me/api/?gender=female

import requests
response = requests.get('https://randomuser.me/api/1.4')
data = response.json()
results = data['results']
for result in results:
  user = result['name']
  for key,value in user.items():
    print(f"{key}:{user}")

